### ISSUE TITLE
[BUG] Authorize.net Sim Gateway Connection Error

### ISSUE THREAD

**Issue by qweik** [ParadoxLabs-Inc/authnetcim#10]
The problem appeared yesterday: "Authorize.net Sim Gateway Connection Error: Peer's certificate issuer has been marked as not trusted by the user"

![CleanShot 2024-10-24 at 16 10 04@2x](https://github.com/user-attachments/assets/3222e332-ae90-460d-b5ad-a379e424d002)

**Comment by rhoerr** [comment]
Hi @qweik, this issue is caused by expiring root certificates and SSL changes by Authorize.net. Reference:

- https://support.authorize.net/knowledgebase/Knowledgearticle/?code=KA-05545
- https://support.paradoxlabs.com/support/solutions/articles/4000191140-authorize-net-cim-ssl-certificate-problem-certificate-has-expired

Please update to the latest extension version (currently 5.1.2), and you should find the issue goes away.
