### ISSUE TITLE
Declined and Failed Orders Not Showing in Sales > Orders Grid in Magento 2.4.0

### ISSUE THREAD

**Issue by wajahatbashir** [ParadoxLabs-Inc/authnetcim#6]
**Module:** ParadoxLabs AuthNet CIM  
**Magento Version:** 2.4.0  
**Environment:** Production Mode  
**Payment Action:** Authorize

**Issue Description:**

I have installed the ParadoxLabs AuthNet CIM module on my Magento 2.4.0 store. I am using the module in production mode, with the payment action set to "Authorize" in the module configuration. However, declined and failed orders are not showing in the **Sales > Orders Grid**.  

This makes it difficult to track any failed or declined transactions from the admin panel. I would like to know if it's possible to show failed/declined orders in the Sales > Orders grid and if this issue is related to configuration settings or code changes within the module.

**Steps to Reproduce:**

1. Install the ParadoxLabs AuthNet CIM module in Magento 2.4.0.
2. Configure the Payment Action to "Authorize" in the module settings.
3. Process an order that results in a failed or declined transaction.
4. Check the Sales > Orders grid to find the declined/failed order.

**Expected Result:**

Declined or failed orders should appear in the Sales > Orders grid in Magento admin for proper tracking.

**Actual Result:**

Declined or failed orders are not displayed in the Sales > Orders grid.

**Additional Information:**

- I am using the **Authorize.Net** payment method in **Authorize Only** mode.
- I would like to know if there is any way to display failed or declined transactions in the Orders grid.
- Any insights on whether this is related to configuration settings or if it requires code adjustments would be helpful.

**Comment by rhoerr** [comment]
Hi @wajahatbashir , thanks for contacting us.

This behavior is working as intended, and not something we plan to change. Most payment methods do not create a 'failed' order when it fails to go through. Creating such orders would be liable to cause problems for existing users, and would complicate checkout when the customer fixes their payment info and tries submitting again.

The only payment method I know that does create failed orders is PayPal Express, and that's because it is a redirect method where the order gets created before you actually complete the payment form and process.

In our case, all failures and declines get logged to the transaction log file (var/log/tokenbase.log), and send Payment Failed emails from Magento (if you have those enabled). You can also enable transaction notifications in Authorize.net.

I hope that helps.
